#!/usr/bin/env python3
"""Generate CH10 L2 placeholder factory JSON (5/6/5/6)."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CHAPTER_ID = "ch10_field_echo_innovation"
CHAPTER_TITLE = "创新之路"
PREV = "ch09_field_echo_future"
SOURCE_REF = "docs/content/canon/CH10_CONTENT_CANON_V1.md"
COMPLETION_MARK = "创新印记"

RELIC_IDS = [
    "relic_ch10_innovation_badge",
    "relic_ch10_gate_imprint_i",
    "relic_ch10_collective_mirror",
    "relic_ch10_influence_expansion",
    "relic_ch10_social_practice",
    "relic_ch10_field_innovation_seal",
]

FORBIDDEN_AWARENESS = ["rarity", "level", "grade", "rank", "equipment", "loot", "trophy"]
FORBIDDEN_PRACTICE = FORBIDDEN_AWARENESS + ["spell", "curse"]
FORBIDDEN_COMPLETION = ["rarity", "level", "grade", "rank", "equipment", "achievement", "title_as_rank"]

story = {
    "schema": "loveqigu.story.chapters.v1",
    "version": "1.0.0",
    "source": "CH10_CONTENT_CANON_V1",
    "layer": "L2",
    "status": "placeholder",
    "source_ref": SOURCE_REF,
    "canonical_boundary": "CH10 Story Layer placeholder factory. Five-awareness structure registered; no new lore. No Canon Gap fill.",
    "previous_chapter_ref": PREV,
    "chapters": [
        {
            "id": CHAPTER_ID,
            "chapter_code": "CH10",
            "title": CHAPTER_TITLE,
            "display_title": f"《{CHAPTER_TITLE}》",
            "status": "placeholder",
            "layer": "L2",
            "language_layer": "L2_PRODUCT",
            "canonical_boundary": "Five-awareness chapter structure; independent imprint album I; continues after CH09 without new Canon history.",
            "summary": "CH10 Story Layer container. Five awareness points on the innovation path; collective practice extends without new Cosmology.",
            "previous_chapter": PREV,
            "next_chapter": "TBD",
            "awareness_structure": {"type": "five_awareness", "label": "五处觉察", "total": 5},
            "imprint_album": {
                "label": "印谱",
                "album_code": "I",
                "total_slots": 5,
                "progress_display": "k/5",
            },
            "completion": {
                "action": "章成",
                "completion_mark": COMPLETION_MARK,
                "completion_mark_relic_ref": "relic_ch10_field_innovation_seal",
                "exploration_memorial": CHAPTER_TITLE,
                "memorial_title": "创新同行者",
            },
            "progress": {"explored_nodes": 0, "total_nodes": 5, "display": "0/5"},
            "nodes": [
                {
                    "id": "n1_innovation",
                    "sequence": 1,
                    "awareness_index": 1,
                    "title": "场域·创新种子",
                    "node_type": "exploration",
                    "status": "available",
                    "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
                    "location_ref": "loc_gate_entry",
                    "imprint_slot": 1,
                    "ar_event_refs": ["ar_ch10_field_gate_v1", "ar_ch10_imprint_innovation_v1"],
                    "relic_refs": ["relic_ch10_innovation_badge", "relic_ch10_gate_imprint_i"],
                    "canonical_boundary": "Innovation seed at field entry; 创新之路 is L2 chapter title, not new geography or 云门 object.",
                    "completion_required": True,
                },
                {
                    "id": "n2_collective_reflection",
                    "sequence": 2,
                    "awareness_index": 2,
                    "title": "回响镜·集体照见",
                    "node_type": "exploration",
                    "status": "available",
                    "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
                    "location_ref": "loc_central_plaza",
                    "imprint_slot": 2,
                    "ar_event_refs": ["ar_ch10_collective_reflection_v1"],
                    "relic_refs": ["relic_ch10_collective_mirror"],
                    "canonical_boundary": "Collective reflection node; social resonance without new Cosmology.",
                    "completion_required": True,
                },
                {
                    "id": "n3_influence_expansion",
                    "sequence": 3,
                    "awareness_index": 3,
                    "title": "谷里咖啡·影响延展",
                    "node_type": "exploration",
                    "status": "available",
                    "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
                    "location_ref": "loc_cafe_human_field",
                    "imprint_slot": 3,
                    "ar_event_refs": ["ar_ch10_influence_expansion_v1"],
                    "relic_refs": ["relic_ch10_influence_expansion"],
                    "rights_refs": [],
                    "canonical_boundary": "Influence expansion memorial; L1 redemption stays outside ritual chain.",
                    "completion_required": True,
                },
                {
                    "id": "n4_social_practice",
                    "sequence": 4,
                    "awareness_index": 4,
                    "title": "云间书符·社会修习",
                    "node_type": "practice",
                    "status": "available",
                    "language_layer": "L2_PRODUCT",
                    "location_ref": "loc_zhujin_entry",
                    "imprint_slot": 4,
                    "ar_event_refs": ["ar_ch10_innovation_guide_v1"],
                    "relic_refs": ["relic_ch10_social_practice"],
                    "canonical_boundary": "Social practice memorial frame; remembrance only; no medical claim or new lineage.",
                    "completion_required": True,
                },
                {
                    "id": "n5_complete",
                    "sequence": 5,
                    "awareness_index": 5,
                    "title": "创新之路·章成",
                    "node_type": "chapter_completion",
                    "status": "locked",
                    "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
                    "location_ref": None,
                    "imprint_slot": 5,
                    "ar_event_refs": ["ar_ch10_completion_v1"],
                    "relic_refs": ["relic_ch10_field_innovation_seal"],
                    "canonical_boundary": "Chapter completion confirmation; completion_mark is memorial, not rank or level.",
                    "completion_required": True,
                    "unlock_requires": [
                        "n1_innovation",
                        "n2_collective_reflection",
                        "n3_influence_expansion",
                        "n4_social_practice",
                    ],
                },
            ],
        }
    ],
}

chapter_context = {
    "chapter_id": CHAPTER_ID,
    "chapter_code": "CH10",
    "chapter_title": CHAPTER_TITLE,
    "display_title": f"《{CHAPTER_TITLE}》",
}

relics = {
    "schema": "loveqigu.relics.v1",
    "version": "1.0.0",
    "source": "CH10_CONTENT_CANON_V1",
    "layer": "L2",
    "status": "placeholder",
    "source_ref": SOURCE_REF,
    "story_ref": "data/story/ch10_chapters.json",
    "canonical_boundary": "CH10 Relic Layer placeholder factory. Story progression assets. Independent album I. No rarity, rank, level, or equipment semantics.",
    "asset_boundary": {
        "relic": "信物是故事进度资产，Canon-driven，见证创新而非拥有。",
        "digital_collectible": "数字藏品是营销与传播资产，与信物分离。",
        "rule": "Relic records must not be treated as Digital Collectible records.",
    },
    "chapter_context": chapter_context,
    "relics": [
        {
            "id": "relic_ch10_innovation_badge",
            "name": "创新徽章",
            "chapter_id": CHAPTER_ID,
            "chapter_title": CHAPTER_TITLE,
            "node_id": "n1_innovation",
            "node_title": "场域·创新种子",
            "type": "awareness_relic",
            "asset_class": "story_progression",
            "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
            "status": "unrecorded",
            "imprint_slot": 1,
            "progression_role": "first_exploration_memorial",
            "description": "记念你在场域处辨认到的创新种子。集体觉察开始延伸，连接仍在场域中被记存。",
            "awareness_line": "集体觉察开始延伸，连接仍在场域中被记存。",
            "canonical_boundary": "Innovation seed presence memorial; not a badge of rank or ownership.",
            "forbidden_semantics": FORBIDDEN_AWARENESS,
        },
        {
            "id": "relic_ch10_gate_imprint_i",
            "name": "场域残印·壬",
            "chapter_id": CHAPTER_ID,
            "chapter_title": CHAPTER_TITLE,
            "node_id": "n1_innovation",
            "node_title": "场域·创新种子",
            "type": "imprint_relic",
            "asset_class": "story_progression",
            "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
            "status": "unrecorded",
            "imprint_slot": 1,
            "imprint_album_ref": f"印谱 · {CHAPTER_TITLE}",
            "progression_role": "imprint_album_slot",
            "description": "记念场域处留下的探索记录。残印是连接曾经存在过的证据，不是收藏数量。",
            "awareness_line": "场域之中，你留下了创新被记存的记录。",
            "canonical_boundary": "Imprint evidence follows Canon tenth law; album I is independent from prior chapter albums.",
            "forbidden_semantics": FORBIDDEN_AWARENESS + ["collectible_count", "power"],
        },
        {
            "id": "relic_ch10_collective_mirror",
            "name": "集体照见信物",
            "chapter_id": CHAPTER_ID,
            "chapter_title": CHAPTER_TITLE,
            "node_id": "n2_collective_reflection",
            "node_title": "回响镜·集体照见",
            "type": "awareness_relic",
            "asset_class": "story_progression",
            "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
            "status": "unrecorded",
            "imprint_slot": 2,
            "progression_role": "node_exploration_memorial",
            "description": "记念你在集体照见处完成的觉察。影响在社会互动中被照见，共鸣在照见处被记存。",
            "awareness_line": "影响在社会互动中被照见，共鸣在照见处被记存。",
            "canonical_boundary": "Collective reflection memorial only; no new Cosmology.",
            "forbidden_semantics": FORBIDDEN_AWARENESS,
        },
        {
            "id": "relic_ch10_influence_expansion",
            "name": "影响延展信物",
            "chapter_id": CHAPTER_ID,
            "chapter_title": CHAPTER_TITLE,
            "node_id": "n3_influence_expansion",
            "node_title": "谷里咖啡·影响延展",
            "type": "awareness_relic",
            "asset_class": "story_progression",
            "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
            "status": "unrecorded",
            "imprint_slot": 3,
            "progression_role": "node_exploration_memorial",
            "description": "记念你在人间道场辨认到的影响延展。一次服务、一杯咖啡、一次真实相遇，善意连接仍可在真实相遇处被照见。",
            "awareness_line": "人间道场不必在名山。同行的记念，可以在真实相遇处被记存。",
            "canonical_boundary": "Influence expansion memorial only; L1 redemption stays outside ritual chain.",
            "forbidden_semantics": FORBIDDEN_AWARENESS,
        },
        {
            "id": "relic_ch10_social_practice",
            "name": "云间书符·社会感印",
            "chapter_id": CHAPTER_ID,
            "chapter_title": CHAPTER_TITLE,
            "node_id": "n4_social_practice",
            "node_title": "云间书符·社会修习",
            "type": "practice_relic",
            "asset_class": "story_progression",
            "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
            "status": "unrecorded",
            "imprint_slot": 4,
            "progression_role": "practice_memorial",
            "description": "记念云间书符处完成的社会修习。符者，记念也，非咒也——修习是记念觉察被记存，不是获得新力量。",
            "awareness_line": "符者，记念也，非咒也。",
            "canonical_boundary": "Social practice memorial only; no medical claim, magic system, sect, or lineage.",
            "forbidden_semantics": FORBIDDEN_PRACTICE,
        },
        {
            "id": "relic_ch10_field_innovation_seal",
            "name": COMPLETION_MARK,
            "chapter_id": CHAPTER_ID,
            "chapter_title": CHAPTER_TITLE,
            "node_id": "n5_complete",
            "node_title": "创新之路·章成",
            "type": "chapter_completion_relic",
            "asset_class": "story_progression",
            "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
            "status": "unrecorded",
            "imprint_slot": 5,
            "progression_role": "chapter_completion_mark",
            "completion_mark": True,
            "exploration_memorial": CHAPTER_TITLE,
            "memorial_title": "创新同行者",
            "description": f"记念《{CHAPTER_TITLE}》章成。五处觉察已齐备，世界留下{COMPLETION_MARK}，见证连接而非等级。",
            "awareness_line": f"五处觉察已齐备。确认章成，点亮{COMPLETION_MARK}。",
            "canonical_boundary": "Chapter completion seal only; not rank, level, combat, or superiority proof.",
            "forbidden_semantics": FORBIDDEN_COMPLETION,
        },
    ],
}

rights_template = [
    ("structure_preview", "章节结构预览", "preview", "available", None, "查看章节结构与活动入口。"),
    ("jieyuan_free_latte", "结缘礼 · 免费拿铁券", "coupon", "locked", "n3_influence_expansion", "结缘礼已开放：免费拿铁券（探索完成后可领）。"),
    ("jieyuan_cafe_discount", "结缘礼 · 咖啡五折券", "coupon", "locked", "n5_complete", "你已积累足够心愿值，可在结缘商城查看咖啡五折券等结缘礼。"),
    ("share_poster", "章成分享资格", "share", "locked", "n5_complete", "生成分享海报，或前往「我的信物」回顾记念。"),
    ("coupon_wallet", "我的卡券", "coupon_list", "available", None, "卡券列表占位，未连接真实核销数据。"),
]

rights = {
    "schema": "loveqigu.rights.v1",
    "version": "1.0.0",
    "source": "CH10_CONTENT_CANON_V1",
    "layer": "L1",
    "language_layer": "L1_COMMERCIAL",
    "status": "placeholder",
    "source_ref": SOURCE_REF,
    "story_ref": "data/story/ch10_chapters.json",
    "relic_ref": "data/relics/ch10_relics.json",
    "canonical_boundary": "CH10 Rights Layer placeholder factory. Commercial functions isolated from ritual chain. No new lore. No Canon Gap fill.",
    "chapter_context": chapter_context,
    "relic_refs_all": RELIC_IDS,
    "asset_boundary": {
        "rights": "L1 commercial layer; must not be sold as Relic or mixed into ritual closure.",
        "relic": "Story progression asset; Rights must not unlock or replace Relic progression.",
        "rule": "Rights records reference relic context but do not mutate Relic state.",
    },
    "rights": [],
}

for suffix, name, rtype, rstatus, node, copy in rights_template:
    surface = "分享页" if rtype == "share" else "我的卡券" if rtype == "coupon_list" else "结缘商城"
    rights["rights"].append(
        {
            "id": f"right_ch10_{suffix}",
            "name": name,
            "chapter_id": CHAPTER_ID,
            "type": rtype,
            "status": rstatus,
            "language_layer": "L1_COMMERCIAL",
            "relic_refs": RELIC_IDS,
            "description": f"记念《{CHAPTER_TITLE}》{name}。",
            "eligibility_node_id": node,
            "redemption": {"enabled": False, "surface": surface, "copy": copy},
            "canonical_boundary": "L1 commercial only; zero Relic progression effect; isolated from ritual closure.",
        }
    )

ar = {
    "schema": "loveqigu.ar.events.v1",
    "version": "1.0.0",
    "source": "CH10_CONTENT_CANON_V1",
    "layer": "L2",
    "language_layer": "L2_PRODUCT",
    "status": "placeholder",
    "source_ref": SOURCE_REF,
    "story_ref": "data/story/ch10_chapters.json",
    "relic_ref": "data/relics/ch10_relics.json",
    "rights_ref": "data/rights/ch10_rights.json",
    "canonical_boundary": "CH10 AR Event Layer placeholder factory. Field experience and closure entry. No new lore. No Canon Gap fill.",
    "chapter_context": chapter_context,
    "asset_boundary": {
        "ar_event": "Field visualization and approved closure entry; does not create 云门 state.",
        "relic": "AR output may reference Relic context; Relic progression remains deterministic from exploration.",
        "rights": "L1 redemption refs stay outside ritual closure chain.",
        "digital_collectible": "Share outputs are user-initiated; zero Relic progression effect.",
    },
    "events": [
        {
            "id": "ar_ch10_field_gate_v1",
            "code": "AR_CH10_FIELD_GATE_V1",
            "name": "创新场域",
            "chapter_id": CHAPTER_ID,
            "node_id": "n1_innovation",
            "node_title": "场域·创新种子",
            "status": "available",
            "interaction": "location_gate",
            "camera_enabled": False,
            "fake_ar_enabled": True,
            "description": "记念场域·创新种子处的场域体验。创新之路是 L2 章节题名，不是新地理或可被占有的关卡。",
            "copy": "预览创新场域，不请求 live AR 权限。",
            "relic_refs": ["relic_ch10_innovation_badge", "relic_ch10_gate_imprint_i"],
            "rights_refs": [],
            "digital_collectible_refs": [],
            "canonical_boundary": "Innovation field visualization only; 创新之路 is L2 chapter title, not new geography.",
        },
        {
            "id": "ar_ch10_imprint_innovation_v1",
            "code": "AR_CH10_IMPRINT_INNOVATION_V1",
            "name": "创新残印",
            "chapter_id": CHAPTER_ID,
            "node_id": "n1_innovation",
            "node_title": "场域·创新种子",
            "status": "available",
            "interaction": "imprint_particles",
            "camera_enabled": False,
            "fake_ar_enabled": True,
            "description": "记念场域处探索记录的创新印迹显现。残印是连接曾经存在过的证据，不是收藏数量。",
            "copy": "预览创新印迹粒子场域，不定义残印形成机制。",
            "relic_refs": ["relic_ch10_gate_imprint_i"],
            "rights_refs": [],
            "digital_collectible_refs": [],
            "canonical_boundary": "Does not define imprint formation mechanics; album I independent from prior chapters.",
        },
        {
            "id": "ar_ch10_collective_reflection_v1",
            "code": "AR_CH10_COLLECTIVE_REFLECTION_V1",
            "name": "集体照见",
            "chapter_id": CHAPTER_ID,
            "node_id": "n2_collective_reflection",
            "node_title": "回响镜·集体照见",
            "status": "available",
            "interaction": "awareness_prompt",
            "camera_enabled": False,
            "fake_ar_enabled": True,
            "description": "记念回响镜·集体照见处的场域体验。影响在社会互动中被照见，共鸣在照见处被记存。",
            "copy": "预览集体照见场域，承接第二处觉察。",
            "relic_refs": ["relic_ch10_collective_mirror"],
            "rights_refs": [],
            "digital_collectible_refs": [],
            "canonical_boundary": "Uses existing field context only; no new Cosmology or lore.",
        },
        {
            "id": "ar_ch10_influence_expansion_v1",
            "code": "AR_CH10_INFLUENCE_EXPANSION_V1",
            "name": "影响延展场域",
            "chapter_id": CHAPTER_ID,
            "node_id": "n3_influence_expansion",
            "node_title": "谷里咖啡·影响延展",
            "status": "available",
            "interaction": "human_field_presence",
            "camera_enabled": False,
            "fake_ar_enabled": True,
            "description": "记念谷里咖啡·影响延展处的场域体验。一次服务、一杯咖啡、一次真实相遇，善意连接仍可在真实相遇处被照见。",
            "copy": "预览影响延展场域；结缘礼在探索完成后于结缘商城触达。",
            "relic_refs": ["relic_ch10_influence_expansion"],
            "rights_refs": ["right_ch10_jieyuan_free_latte"],
            "digital_collectible_refs": [],
            "canonical_boundary": "L1 redemption stays outside ritual chain; no medical or lineage claims.",
        },
        {
            "id": "ar_ch10_innovation_guide_v1",
            "code": "AR_CH10_INNOVATION_GUIDE_V1",
            "name": "社会修习引导",
            "chapter_id": CHAPTER_ID,
            "node_id": "n4_social_practice",
            "node_title": "云间书符·社会修习",
            "status": "available",
            "interaction": "guide_sequence",
            "camera_enabled": False,
            "fake_ar_enabled": True,
            "description": "记念云间书符·社会修习处的场域体验。修习是记念觉察被记存，不是获得新力量——符者，记念也，非咒也。",
            "copy": "预览社会修习引导场域，不宣称医疗、派系或传承体系。",
            "relic_refs": ["relic_ch10_social_practice"],
            "rights_refs": [],
            "digital_collectible_refs": [],
            "canonical_boundary": "No medical claim, magic system, sect, or lineage; no L1 rights popup at practice node.",
        },
        {
            "id": "ar_ch10_completion_v1",
            "code": "AR_CH10_COMPLETION_V1",
            "name": "创新之路·章成",
            "chapter_id": CHAPTER_ID,
            "node_id": "n5_complete",
            "node_title": "创新之路·章成",
            "status": "locked",
            "interaction": "completion_scene",
            "camera_enabled": False,
            "fake_ar_enabled": True,
            "description": f"记念《{CHAPTER_TITLE}》章成 closure 场域。五处觉察已齐备，世界留下{COMPLETION_MARK}，见证连接而非等级。",
            "copy": "预览章成 closure 场域，可接续分享海报生成流程。",
            "relic_refs": ["relic_ch10_field_innovation_seal"],
            "rights_refs": ["right_ch10_jieyuan_cafe_discount", "right_ch10_share_poster"],
            "digital_collectible_refs": ["dc_ch10_innovation_poster"],
            "canonical_boundary": "Completion is not ranking, level, combat, or proof of superiority.",
            "unlock_requires": [
                "n1_innovation",
                "n2_collective_reflection",
                "n3_influence_expansion",
                "n4_social_practice",
            ],
        },
    ],
}


def write(path: Path, data: dict) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    write(ROOT / "data/story/ch10_chapters.json", story)
    write(ROOT / "data/relics/ch10_relics.json", relics)
    write(ROOT / "data/rights/ch10_rights.json", rights)
    write(ROOT / "data/ar/ch10_ar-events.json", ar)
    print("CH10 placeholder factory written")
