#!/usr/bin/env python3
"""Generate CH07 L2 placeholder factory JSON (5/6/5/6)."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CHAPTER_ID = "ch07_field_echo"
CHAPTER_TITLE = "回响之路"
PREV = "ch06_field_completion"
SOURCE_REF = "docs/content/canon/CH07_CONTENT_CANON_V1.md"

RELIC_IDS = [
    "relic_ch07_echo_badge",
    "relic_ch07_gate_imprint_g",
    "relic_ch07_echo_mirror",
    "relic_ch07_human_connection",
    "relic_ch07_practice_echo",
    "relic_ch07_field_echo_seal",
]

FORBIDDEN_AWARENESS = ["rarity", "level", "grade", "rank", "equipment", "loot", "trophy"]
FORBIDDEN_PRACTICE = FORBIDDEN_AWARENESS + ["spell", "curse"]
FORBIDDEN_COMPLETION = ["rarity", "level", "grade", "rank", "equipment", "achievement", "title_as_rank"]

story = {
    "schema": "loveqigu.story.chapters.v1",
    "version": "1.0.0",
    "source": "CH07_CONTENT_CANON_V1",
    "layer": "L2",
    "status": "placeholder",
    "source_ref": SOURCE_REF,
    "canonical_boundary": "CH07 Story Layer placeholder factory. Five-awareness structure registered; no new lore. No Canon Gap fill.",
    "previous_chapter_ref": PREV,
    "chapters": [
        {
            "id": CHAPTER_ID,
            "chapter_code": "CH07",
            "title": CHAPTER_TITLE,
            "display_title": f"《{CHAPTER_TITLE}》",
            "status": "placeholder",
            "layer": "L2",
            "language_layer": "L2_PRODUCT",
            "canonical_boundary": "Five-awareness chapter structure; independent imprint album G; continues after CH06 without new Canon history.",
            "summary": "CH07 Story Layer container. Five awareness points on the echo path; change begins to reach others without new Cosmology.",
            "previous_chapter": PREV,
            "next_chapter": "TBD",
            "awareness_structure": {"type": "five_awareness", "label": "五处觉察", "total": 5},
            "imprint_album": {
                "label": "印谱",
                "album_code": "G",
                "total_slots": 5,
                "progress_display": "k/5",
            },
            "completion": {
                "action": "章成",
                "completion_mark": "回响印记",
                "completion_mark_relic_ref": "relic_ch07_field_echo_seal",
                "exploration_memorial": CHAPTER_TITLE,
                "memorial_title": "回响同行者",
            },
            "progress": {"explored_nodes": 0, "total_nodes": 5, "display": "0/5"},
            "nodes": [
                {
                    "id": "n1_field",
                    "sequence": 1,
                    "awareness_index": 1,
                    "title": "场域·回响种子",
                    "node_type": "exploration",
                    "status": "available",
                    "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
                    "location_ref": "loc_gate_entry",
                    "imprint_slot": 1,
                    "ar_event_refs": ["ar_ch07_field_gate_v1", "ar_ch07_imprint_echo_v1"],
                    "relic_refs": ["relic_ch07_echo_badge", "relic_ch07_gate_imprint_g"],
                    "canonical_boundary": "Echo seed at field entry; 回响之路 is L2 chapter title, not new geography or 云门 object.",
                    "completion_required": True,
                },
                {
                    "id": "n2_reflection",
                    "sequence": 2,
                    "awareness_index": 2,
                    "title": "回响镜·照见",
                    "node_type": "exploration",
                    "status": "available",
                    "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
                    "location_ref": "loc_central_plaza",
                    "imprint_slot": 2,
                    "ar_event_refs": ["ar_ch07_echo_awareness_v1"],
                    "relic_refs": ["relic_ch07_echo_mirror"],
                    "canonical_boundary": "Echo reflection node; awareness leaving self toward connection; no new Cosmology.",
                    "completion_required": True,
                },
                {
                    "id": "n3_human_connection",
                    "sequence": 3,
                    "awareness_index": 3,
                    "title": "谷里咖啡·人间连接",
                    "node_type": "exploration",
                    "status": "available",
                    "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
                    "location_ref": "loc_cafe_human_field",
                    "imprint_slot": 3,
                    "ar_event_refs": ["ar_ch07_human_connection_v1"],
                    "relic_refs": ["relic_ch07_human_connection"],
                    "rights_refs": [],
                    "canonical_boundary": "Human connection memorial; L1 redemption stays outside ritual chain.",
                    "completion_required": True,
                },
                {
                    "id": "n4_practice_echo",
                    "sequence": 4,
                    "awareness_index": 4,
                    "title": "云间书符·同行修习",
                    "node_type": "practice",
                    "status": "available",
                    "language_layer": "L2_PRODUCT",
                    "location_ref": "loc_zhujin_entry",
                    "imprint_slot": 4,
                    "ar_event_refs": ["ar_ch07_echo_guide_v1"],
                    "relic_refs": ["relic_ch07_practice_echo"],
                    "canonical_boundary": "Shared practice memorial frame; remembrance only; no medical claim or new lineage.",
                    "completion_required": True,
                },
                {
                    "id": "n5_complete",
                    "sequence": 5,
                    "awareness_index": 5,
                    "title": "回响之路·章成",
                    "node_type": "chapter_completion",
                    "status": "locked",
                    "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
                    "location_ref": None,
                    "imprint_slot": 5,
                    "ar_event_refs": ["ar_ch07_completion_v1"],
                    "relic_refs": ["relic_ch07_field_echo_seal"],
                    "canonical_boundary": "Chapter completion confirmation; completion_mark is memorial, not rank or level.",
                    "completion_required": True,
                    "unlock_requires": [
                        "n1_field",
                        "n2_reflection",
                        "n3_human_connection",
                        "n4_practice_echo",
                    ],
                },
            ],
        }
    ],
}

chapter_context = {
    "chapter_id": CHAPTER_ID,
    "chapter_code": "CH07",
    "chapter_title": CHAPTER_TITLE,
    "display_title": f"《{CHAPTER_TITLE}》",
}

relics = {
    "schema": "loveqigu.relics.v1",
    "version": "1.0.0",
    "source": "CH07_CONTENT_CANON_V1",
    "layer": "L2",
    "status": "placeholder",
    "source_ref": SOURCE_REF,
    "story_ref": "data/story/ch07_chapters.json",
    "canonical_boundary": "CH07 Relic Layer placeholder factory. Story progression assets. Independent album G. No rarity, rank, level, or equipment semantics.",
    "asset_boundary": {
        "relic": "信物是故事进度资产，Canon-driven，见证连接而非拥有。",
        "digital_collectible": "数字藏品是营销与传播资产，与信物分离。",
        "rule": "Relic records must not be treated as Digital Collectible records.",
    },
    "chapter_context": chapter_context,
    "relics": [
        {
            "id": "relic_ch07_echo_badge",
            "name": "回响徽章",
            "chapter_id": CHAPTER_ID,
            "chapter_title": CHAPTER_TITLE,
            "node_id": "n1_field",
            "node_title": "场域·回响种子",
            "type": "awareness_relic",
            "asset_class": "story_progression",
            "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
            "status": "unrecorded",
            "imprint_slot": 1,
            "progression_role": "first_exploration_memorial",
            "description": "记念你在场域处辨认到的回响种子。觉察开始离开自身，连接仍在场域中被记存。",
            "awareness_line": "觉察开始离开自身，连接仍在场域中被记存。",
            "canonical_boundary": "Echo seed presence memorial; not a badge of rank or ownership.",
            "forbidden_semantics": FORBIDDEN_AWARENESS,
        },
        {
            "id": "relic_ch07_gate_imprint_g",
            "name": "场域残印·庚",
            "chapter_id": CHAPTER_ID,
            "chapter_title": CHAPTER_TITLE,
            "node_id": "n1_field",
            "node_title": "场域·回响种子",
            "type": "imprint_relic",
            "asset_class": "story_progression",
            "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
            "status": "unrecorded",
            "imprint_slot": 1,
            "imprint_album_ref": f"印谱 · {CHAPTER_TITLE}",
            "progression_role": "imprint_album_slot",
            "description": "记念场域处留下的探索记录。残印是连接曾经存在过的证据，不是收藏数量。",
            "awareness_line": "场域之中，你留下了回响被记存的记录。",
            "canonical_boundary": "Imprint evidence follows Canon tenth law; album G is independent from prior chapter albums.",
            "forbidden_semantics": FORBIDDEN_AWARENESS + ["collectible_count", "power"],
        },
        {
            "id": "relic_ch07_echo_mirror",
            "name": "回响镜信物",
            "chapter_id": CHAPTER_ID,
            "chapter_title": CHAPTER_TITLE,
            "node_id": "n2_reflection",
            "node_title": "回响镜·照见",
            "type": "awareness_relic",
            "asset_class": "story_progression",
            "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
            "status": "unrecorded",
            "imprint_slot": 2,
            "progression_role": "node_exploration_memorial",
            "description": "记念你在回响镜处完成的照见。改变开始影响周围的人，连接在照见处被记存。",
            "awareness_line": "改变开始影响周围的人，连接在照见处被记存。",
            "canonical_boundary": "Echo mirror memorial only; no new Cosmology.",
            "forbidden_semantics": FORBIDDEN_AWARENESS,
        },
        {
            "id": "relic_ch07_human_connection",
            "name": "人间连接信物",
            "chapter_id": CHAPTER_ID,
            "chapter_title": CHAPTER_TITLE,
            "node_id": "n3_human_connection",
            "node_title": "谷里咖啡·人间连接",
            "type": "awareness_relic",
            "asset_class": "story_progression",
            "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
            "status": "unrecorded",
            "imprint_slot": 3,
            "progression_role": "node_exploration_memorial",
            "description": "记念你在人间道场辨认到的连接。一次服务、一杯咖啡、一次真实相遇，善意连接仍可在真实相遇处被照见。",
            "awareness_line": "人间道场不必在名山。同行的记念，可以在真实相遇处被记存。",
            "canonical_boundary": "Human connection memorial only; L1 redemption stays outside ritual chain.",
            "forbidden_semantics": FORBIDDEN_AWARENESS,
        },
        {
            "id": "relic_ch07_practice_echo",
            "name": "云间书符·同行感印",
            "chapter_id": CHAPTER_ID,
            "chapter_title": CHAPTER_TITLE,
            "node_id": "n4_practice_echo",
            "node_title": "云间书符·同行修习",
            "type": "practice_relic",
            "asset_class": "story_progression",
            "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
            "status": "unrecorded",
            "imprint_slot": 4,
            "progression_role": "practice_memorial",
            "description": "记念云间书符处完成的同行修习。符者，记念也，非咒也——修习是记念觉察被记存，不是获得新力量。",
            "awareness_line": "符者，记念也，非咒也。",
            "canonical_boundary": "Practice memorial only; no medical claim, magic system, sect, or lineage.",
            "forbidden_semantics": FORBIDDEN_PRACTICE,
        },
        {
            "id": "relic_ch07_field_echo_seal",
            "name": "回响印记",
            "chapter_id": CHAPTER_ID,
            "chapter_title": CHAPTER_TITLE,
            "node_id": "n5_complete",
            "node_title": "回响之路·章成",
            "type": "chapter_completion_relic",
            "asset_class": "story_progression",
            "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
            "status": "unrecorded",
            "imprint_slot": 5,
            "progression_role": "chapter_completion_mark",
            "completion_mark": True,
            "exploration_memorial": CHAPTER_TITLE,
            "memorial_title": "回响同行者",
            "description": f"记念《{CHAPTER_TITLE}》章成。五处觉察已齐备，世界留下回响印记，见证连接而非等级。",
            "awareness_line": "五处觉察已齐备。确认章成，点亮回响印记。",
            "canonical_boundary": "Chapter completion seal only; not rank, level, combat, or superiority proof.",
            "forbidden_semantics": FORBIDDEN_COMPLETION,
        },
    ],
}

rights_template = [
    ("structure_preview", "章节结构预览", "preview", "available", None, "查看章节结构与活动入口。"),
    ("jieyuan_free_latte", "结缘礼 · 免费拿铁券", "coupon", "locked", "n3_human_connection", "结缘礼已开放：免费拿铁券（探索完成后可领）。"),
    ("jieyuan_cafe_discount", "结缘礼 · 咖啡五折券", "coupon", "locked", "n5_complete", "你已积累足够心愿值，可在结缘商城查看咖啡五折券等结缘礼。"),
    ("share_poster", "章成分享资格", "share", "locked", "n5_complete", "生成分享海报，或前往「我的信物」回顾记念。"),
    ("coupon_wallet", "我的卡券", "coupon_list", "available", None, "卡券列表占位，未连接真实核销数据。"),
]

rights = {
    "schema": "loveqigu.rights.v1",
    "version": "1.0.0",
    "source": "CH07_CONTENT_CANON_V1",
    "layer": "L1",
    "language_layer": "L1_COMMERCIAL",
    "status": "placeholder",
    "source_ref": SOURCE_REF,
    "story_ref": "data/story/ch07_chapters.json",
    "relic_ref": "data/relics/ch07_relics.json",
    "canonical_boundary": "CH07 Rights Layer placeholder factory. Commercial functions isolated from ritual chain. No new lore. No Canon Gap fill.",
    "chapter_context": chapter_context,
    "relic_refs_all": RELIC_IDS,
    "asset_boundary": {
        "rights": "L1 commercial layer; must not be sold as Relic or mixed into ritual closure.",
        "relic": "Story progression asset; Rights must not unlock or replace Relic progression.",
        "rule": "Rights records reference relic context but do not mutate Relic state.",
    },
    "rights": [],
}

for suffix, name, rtype, rstatus, node, copy in rights_template:
    surface = "分享页" if rtype == "share" else "我的卡券" if rtype == "coupon_list" else "结缘商城"
    rights["rights"].append(
        {
            "id": f"right_ch07_{suffix}",
            "name": name,
            "chapter_id": CHAPTER_ID,
            "type": rtype,
            "status": rstatus,
            "language_layer": "L1_COMMERCIAL",
            "relic_refs": RELIC_IDS,
            "description": f"记念《{CHAPTER_TITLE}》{name}。",
            "eligibility_node_id": node,
            "redemption": {"enabled": False, "surface": surface, "copy": copy},
            "canonical_boundary": "L1 commercial only; zero Relic progression effect; isolated from ritual closure.",
        }
    )

ar = {
    "schema": "loveqigu.ar.events.v1",
    "version": "1.0.0",
    "source": "CH07_CONTENT_CANON_V1",
    "layer": "L2",
    "language_layer": "L2_PRODUCT",
    "status": "placeholder",
    "source_ref": SOURCE_REF,
    "story_ref": "data/story/ch07_chapters.json",
    "relic_ref": "data/relics/ch07_relics.json",
    "rights_ref": "data/rights/ch07_rights.json",
    "canonical_boundary": "CH07 AR Event Layer placeholder factory. Field experience and closure entry. No new lore. No Canon Gap fill.",
    "chapter_context": chapter_context,
    "asset_boundary": {
        "ar_event": "Field visualization and approved closure entry; does not create 云门 state.",
        "relic": "AR output may reference Relic context; Relic progression remains deterministic from exploration.",
        "rights": "L1 redemption refs stay outside ritual closure chain.",
        "digital_collectible": "Share outputs are user-initiated; zero Relic progression effect.",
    },
    "events": [
        {
            "id": "ar_ch07_field_gate_v1",
            "code": "AR_CH07_FIELD_GATE_V1",
            "name": "回响场域",
            "chapter_id": CHAPTER_ID,
            "node_id": "n1_field",
            "node_title": "场域·回响种子",
            "status": "available",
            "interaction": "location_gate",
            "camera_enabled": False,
            "fake_ar_enabled": True,
            "description": "记念场域·回响种子处的场域体验。回响之路是 L2 章节题名，不是新地理或可被占有的关卡。",
            "copy": "预览回响场域，不请求 live AR 权限。",
            "relic_refs": ["relic_ch07_echo_badge", "relic_ch07_gate_imprint_g"],
            "rights_refs": [],
            "digital_collectible_refs": [],
            "canonical_boundary": "Echo field visualization only; 回响之路 is L2 chapter title, not new geography.",
        },
        {
            "id": "ar_ch07_imprint_echo_v1",
            "code": "AR_CH07_IMPRINT_ECHO_V1",
            "name": "回响残印",
            "chapter_id": CHAPTER_ID,
            "node_id": "n1_field",
            "node_title": "场域·回响种子",
            "status": "available",
            "interaction": "imprint_particles",
            "camera_enabled": False,
            "fake_ar_enabled": True,
            "description": "记念场域处探索记录的回响印迹显现。残印是连接曾经存在过的证据，不是收藏数量。",
            "copy": "预览回响印迹粒子场域，不定义残印形成机制。",
            "relic_refs": ["relic_ch07_gate_imprint_g"],
            "rights_refs": [],
            "digital_collectible_refs": [],
            "canonical_boundary": "Does not define imprint formation mechanics; album G independent from prior chapters.",
        },
        {
            "id": "ar_ch07_echo_awareness_v1",
            "code": "AR_CH07_ECHO_AWARENESS_V1",
            "name": "回响镜照见",
            "chapter_id": CHAPTER_ID,
            "node_id": "n2_reflection",
            "node_title": "回响镜·照见",
            "status": "available",
            "interaction": "awareness_prompt",
            "camera_enabled": False,
            "fake_ar_enabled": True,
            "description": "记念回响镜·照见处的场域体验。改变开始影响周围的人，连接在照见处被记存。",
            "copy": "预览回响镜照见场域，承接第二处觉察。",
            "relic_refs": ["relic_ch07_echo_mirror"],
            "rights_refs": [],
            "digital_collectible_refs": [],
            "canonical_boundary": "Uses existing field context only; no new Cosmology or lore.",
        },
        {
            "id": "ar_ch07_human_connection_v1",
            "code": "AR_CH07_HUMAN_CONNECTION_V1",
            "name": "人间连接场域",
            "chapter_id": CHAPTER_ID,
            "node_id": "n3_human_connection",
            "node_title": "谷里咖啡·人间连接",
            "status": "available",
            "interaction": "human_field_presence",
            "camera_enabled": False,
            "fake_ar_enabled": True,
            "description": "记念谷里咖啡·人间连接处的场域体验。一次服务、一杯咖啡、一次真实相遇，善意连接仍可在真实相遇处被照见。",
            "copy": "预览人间连接场域；结缘礼在探索完成后于结缘商城触达。",
            "relic_refs": ["relic_ch07_human_connection"],
            "rights_refs": ["right_ch07_jieyuan_free_latte"],
            "digital_collectible_refs": [],
            "canonical_boundary": "L1 redemption stays outside ritual chain; no medical or lineage claims.",
        },
        {
            "id": "ar_ch07_echo_guide_v1",
            "code": "AR_CH07_ECHO_GUIDE_V1",
            "name": "同行修习引导",
            "chapter_id": CHAPTER_ID,
            "node_id": "n4_practice_echo",
            "node_title": "云间书符·同行修习",
            "status": "available",
            "interaction": "guide_sequence",
            "camera_enabled": False,
            "fake_ar_enabled": True,
            "description": "记念云间书符·同行修习处的场域体验。修习是记念觉察被记存，不是获得新力量——符者，记念也，非咒也。",
            "copy": "预览同行修习引导场域，不宣称医疗、派系或传承。",
            "relic_refs": ["relic_ch07_practice_echo"],
            "rights_refs": [],
            "digital_collectible_refs": [],
            "canonical_boundary": "No medical claim, magic system, sect, or lineage; no L1 rights popup at practice node.",
        },
        {
            "id": "ar_ch07_completion_v1",
            "code": "AR_CH07_COMPLETION_V1",
            "name": "回响之路·章成",
            "chapter_id": CHAPTER_ID,
            "node_id": "n5_complete",
            "node_title": "回响之路·章成",
            "status": "locked",
            "interaction": "completion_scene",
            "camera_enabled": False,
            "fake_ar_enabled": True,
            "description": f"记念《{CHAPTER_TITLE}》章成 closure 场域。五处觉察已齐备，世界留下回响印记，见证连接而非等级。",
            "copy": "预览章成 closure 场域，可接续分享海报生成流程。",
            "relic_refs": ["relic_ch07_field_echo_seal"],
            "rights_refs": ["right_ch07_jieyuan_cafe_discount", "right_ch07_share_poster"],
            "digital_collectible_refs": ["dc_ch07_echo_poster"],
            "canonical_boundary": "Completion is not ranking, level, combat, or proof of superiority.",
            "unlock_requires": [
                "n1_field",
                "n2_reflection",
                "n3_human_connection",
                "n4_practice_echo",
            ],
        },
    ],
}


def write(path: Path, data: dict) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    write(ROOT / "data/story/ch07_chapters.json", story)
    write(ROOT / "data/relics/ch07_relics.json", relics)
    write(ROOT / "data/rights/ch07_rights.json", rights)
    write(ROOT / "data/ar/ch07_ar-events.json", ar)
    print("CH07 placeholder factory written")
