#!/usr/bin/env python3
"""Generate CH04 L2 placeholder factory JSON (5/6/5/6)."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CHAPTER_ID = "ch04_field_awakening"
CHAPTER_TITLE = "田野初醒"
PREV = "ch03_field_reunion"
SOURCE_REF = "docs/content/canon/CH04_CONTENT_CANON_V1.md"

RELIC_IDS = [
    "relic_ch04_awakening_badge",
    "relic_ch04_gate_imprint_d",
    "relic_ch04_awakening_mirror",
    "relic_ch04_human_awakening",
    "relic_ch04_practice_awakening",
    "relic_ch04_field_awakening_seal",
]

FORBIDDEN_AWARENESS = ["rarity", "level", "grade", "rank", "equipment", "loot", "trophy"]
FORBIDDEN_PRACTICE = FORBIDDEN_AWARENESS + ["spell", "curse"]
FORBIDDEN_COMPLETION = ["rarity", "level", "grade", "rank", "equipment", "achievement", "title_as_rank"]

story = {
    "schema": "loveqigu.story.chapters.v1",
    "version": "1.0.0",
    "source": "CH04_CONTENT_CANON_V1",
    "layer": "L2",
    "status": "placeholder",
    "source_ref": SOURCE_REF,
    "canonical_boundary": "CH04 Story Layer placeholder factory. Five-awareness structure registered; no new lore. No Canon Gap fill.",
    "previous_chapter_ref": PREV,
    "chapters": [
        {
            "id": CHAPTER_ID,
            "chapter_code": "CH04",
            "title": CHAPTER_TITLE,
            "display_title": f"《{CHAPTER_TITLE}》",
            "status": "placeholder",
            "layer": "L2",
            "language_layer": "L2_PRODUCT",
            "canonical_boundary": "Five-awareness chapter structure; independent imprint album D; continues after CH03 without new Canon history.",
            "summary": "CH04 Story Layer container. Five exploration awareness points at field awakening; memorial confirmation without new Cosmology.",
            "previous_chapter": PREV,
            "next_chapter": "TBD",
            "awareness_structure": {"type": "five_awareness", "label": "五处觉察", "total": 5},
            "imprint_album": {
                "label": "印谱",
                "album_code": "D",
                "total_slots": 5,
                "progress_display": "k/5",
            },
            "completion": {
                "action": "章成",
                "completion_mark": "初醒印记",
                "completion_mark_relic_ref": "relic_ch04_field_awakening_seal",
                "exploration_memorial": CHAPTER_TITLE,
                "memorial_title": "初醒记念者",
            },
            "progress": {"explored_nodes": 0, "total_nodes": 5, "display": "0/5"},
            "nodes": [
                {
                    "id": "n1_field",
                    "sequence": 1,
                    "awareness_index": 1,
                    "title": "场域·初醒到场",
                    "node_type": "exploration",
                    "status": "available",
                    "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
                    "location_ref": "loc_gate_entry",
                    "imprint_slot": 1,
                    "ar_event_refs": ["ar_ch04_field_gate_v1", "ar_ch04_imprint_awakening_v1"],
                    "relic_refs": ["relic_ch04_awakening_badge", "relic_ch04_gate_imprint_d"],
                    "canonical_boundary": "Field presence at awakening entry; 田野初醒 is L2 chapter title, not new geography or 云门 object.",
                    "completion_required": True,
                },
                {
                    "id": "n2_awakening",
                    "sequence": 2,
                    "awareness_index": 2,
                    "title": "初醒镜·照见",
                    "node_type": "exploration",
                    "status": "available",
                    "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
                    "location_ref": "loc_central_plaza",
                    "imprint_slot": 2,
                    "ar_event_refs": ["ar_ch04_awakening_awareness_v1"],
                    "relic_refs": ["relic_ch04_awakening_mirror"],
                    "canonical_boundary": "Awakening awareness node; uses existing field context only; no new Cosmology.",
                    "completion_required": True,
                },
                {
                    "id": "n3_human_awakening",
                    "sequence": 3,
                    "awareness_index": 3,
                    "title": "谷里咖啡·人间初醒",
                    "node_type": "exploration",
                    "status": "available",
                    "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
                    "location_ref": "loc_cafe_human_field",
                    "imprint_slot": 3,
                    "ar_event_refs": ["ar_ch04_human_awakening_v1"],
                    "relic_refs": ["relic_ch04_human_awakening"],
                    "rights_refs": [],
                    "canonical_boundary": "Human-field awakening memorial; L1 redemption stays outside ritual chain.",
                    "completion_required": True,
                },
                {
                    "id": "n4_practice_awakening",
                    "sequence": 4,
                    "awareness_index": 4,
                    "title": "云间书符·初醒修习",
                    "node_type": "practice",
                    "status": "available",
                    "language_layer": "L2_PRODUCT",
                    "location_ref": "loc_zhujin_entry",
                    "imprint_slot": 4,
                    "ar_event_refs": ["ar_ch04_awakening_guide_v1"],
                    "relic_refs": ["relic_ch04_practice_awakening"],
                    "canonical_boundary": "Practice memorial frame; awakening remembrance only; no medical claim or new lineage.",
                    "completion_required": True,
                },
                {
                    "id": "n5_complete",
                    "sequence": 5,
                    "awareness_index": 5,
                    "title": "田野初醒·章成",
                    "node_type": "chapter_completion",
                    "status": "locked",
                    "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
                    "location_ref": None,
                    "imprint_slot": 5,
                    "ar_event_refs": ["ar_ch04_completion_v1"],
                    "relic_refs": ["relic_ch04_field_awakening_seal"],
                    "canonical_boundary": "Chapter completion confirmation; completion_mark is memorial, not rank or level.",
                    "completion_required": True,
                    "unlock_requires": ["n1_field", "n2_awakening", "n3_human_awakening", "n4_practice_awakening"],
                },
            ],
        }
    ],
}

chapter_context = {
    "chapter_id": CHAPTER_ID,
    "chapter_code": "CH04",
    "chapter_title": CHAPTER_TITLE,
    "display_title": f"《{CHAPTER_TITLE}》",
}

asset_boundary_relic = {
    "relic": "信物是故事进度资产，Canon-driven，见证连接而非拥有。",
    "digital_collectible": "数字藏品是营销与传播资产，与信物分离。",
    "rule": "Relic records must not be treated as Digital Collectible records.",
}

relics = {
    "schema": "loveqigu.relics.v1",
    "version": "1.0.0",
    "source": "CH04_CONTENT_CANON_V1",
    "layer": "L2",
    "status": "placeholder",
    "source_ref": SOURCE_REF,
    "story_ref": "data/story/ch04_chapters.json",
    "canonical_boundary": "CH04 Relic Layer placeholder factory. Story progression assets. Independent album D. No rarity, rank, level, or equipment semantics.",
    "asset_boundary": asset_boundary_relic,
    "chapter_context": chapter_context,
    "relics": [
        {
            "id": "relic_ch04_awakening_badge",
            "name": "初醒徽章",
            "chapter_id": CHAPTER_ID,
            "chapter_title": CHAPTER_TITLE,
            "node_id": "n1_field",
            "node_title": "场域·初醒到场",
            "type": "awareness_relic",
            "asset_class": "story_progression",
            "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
            "status": "unrecorded",
            "imprint_slot": 1,
            "progression_role": "first_exploration_memorial",
            "description": "记念你在场域处完成的初醒到场。觉察在田野中开启，连接仍在场域中被记存。",
            "awareness_line": "觉察在田野中开启，连接仍在场域中被记存。",
            "canonical_boundary": "Field awakening presence memorial; not a badge of rank or ownership.",
            "forbidden_semantics": FORBIDDEN_AWARENESS,
        },
        {
            "id": "relic_ch04_gate_imprint_d",
            "name": "田野残印·丁",
            "chapter_id": CHAPTER_ID,
            "chapter_title": CHAPTER_TITLE,
            "node_id": "n1_field",
            "node_title": "场域·初醒到场",
            "type": "imprint_relic",
            "asset_class": "story_progression",
            "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
            "status": "unrecorded",
            "imprint_slot": 1,
            "imprint_album_ref": f"印谱 · {CHAPTER_TITLE}",
            "progression_role": "imprint_album_slot",
            "description": "记念场域处留下的探索记录。残印是连接曾经存在过的证据，不是收藏数量。",
            "awareness_line": "场域之中，你留下了初醒被记存的记录。",
            "canonical_boundary": "Imprint evidence follows Canon tenth law; album D is independent from prior chapter albums.",
            "forbidden_semantics": FORBIDDEN_AWARENESS + ["collectible_count", "power"],
        },
        {
            "id": "relic_ch04_awakening_mirror",
            "name": "初醒镜信物",
            "chapter_id": CHAPTER_ID,
            "chapter_title": CHAPTER_TITLE,
            "node_id": "n2_awakening",
            "node_title": "初醒镜·照见",
            "type": "awareness_relic",
            "asset_class": "story_progression",
            "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
            "status": "unrecorded",
            "imprint_slot": 2,
            "progression_role": "node_exploration_memorial",
            "description": "记念你在初醒镜处完成的照见。照见，不是向外寻找答案，而是看见自己已与场域同在。",
            "awareness_line": "照见，不是向外寻找答案，而是看见自己已与场域同在。",
            "canonical_boundary": "Awakening mirror memorial only; no new Cosmology.",
            "forbidden_semantics": FORBIDDEN_AWARENESS,
        },
        {
            "id": "relic_ch04_human_awakening",
            "name": "人间初醒信物",
            "chapter_id": CHAPTER_ID,
            "chapter_title": CHAPTER_TITLE,
            "node_id": "n3_human_awakening",
            "node_title": "谷里咖啡·人间初醒",
            "type": "awareness_relic",
            "asset_class": "story_progression",
            "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
            "status": "unrecorded",
            "imprint_slot": 3,
            "progression_role": "node_exploration_memorial",
            "description": "记念你在人间道场辨认到的初醒。一次服务、一杯咖啡、一次真实相遇，连接仍可在真实相遇处被照见。",
            "awareness_line": "人间道场不必在名山。初醒的照见，可以在真实相遇处被记存。",
            "canonical_boundary": "Human-field awakening memorial only; L1 redemption stays outside ritual chain.",
            "forbidden_semantics": FORBIDDEN_AWARENESS,
        },
        {
            "id": "relic_ch04_practice_awakening",
            "name": "云间书符·初醒感印",
            "chapter_id": CHAPTER_ID,
            "chapter_title": CHAPTER_TITLE,
            "node_id": "n4_practice_awakening",
            "node_title": "云间书符·初醒修习",
            "type": "practice_relic",
            "asset_class": "story_progression",
            "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
            "status": "unrecorded",
            "imprint_slot": 4,
            "progression_role": "practice_memorial",
            "description": "记念云间书符处完成的初醒修习。符者，记念也，非咒也——修习是记念觉察被记存，不是获得新力量。",
            "awareness_line": "符者，记念也，非咒也。",
            "canonical_boundary": "Practice memorial only; no medical claim, magic system, sect, or lineage.",
            "forbidden_semantics": FORBIDDEN_PRACTICE,
        },
        {
            "id": "relic_ch04_field_awakening_seal",
            "name": "初醒印记",
            "chapter_id": CHAPTER_ID,
            "chapter_title": CHAPTER_TITLE,
            "node_id": "n5_complete",
            "node_title": "田野初醒·章成",
            "type": "chapter_completion_relic",
            "asset_class": "story_progression",
            "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
            "status": "unrecorded",
            "imprint_slot": 5,
            "progression_role": "chapter_completion_mark",
            "completion_mark": True,
            "exploration_memorial": CHAPTER_TITLE,
            "memorial_title": "初醒记念者",
            "description": f"记念《{CHAPTER_TITLE}》章成。五处觉察已齐备，世界留下初醒印记，见证连接而非等级。",
            "awareness_line": "五处觉察已齐备。确认章成，点亮初醒印记。",
            "canonical_boundary": "Chapter completion seal only; not rank, level, combat, or superiority proof.",
            "forbidden_semantics": FORBIDDEN_COMPLETION,
        },
    ],
}

rights_template = [
    ("structure_preview", "章节结构预览", "preview", "available", None, "查看章节结构与活动入口。"),
    ("jieyuan_free_latte", "结缘礼 · 免费拿铁券", "coupon", "locked", "n3_human_awakening", "结缘礼已开放：免费拿铁券（探索完成后可领）。"),
    ("jieyuan_cafe_discount", "结缘礼 · 咖啡五折券", "coupon", "locked", "n5_complete", "你已积累足够心愿值，可在结缘商城查看咖啡五折券等结缘礼。"),
    ("share_poster", "章成分享资格", "share", "locked", "n5_complete", "生成分享海报，或前往「我的信物」回顾记念。"),
    ("coupon_wallet", "我的卡券", "coupon_list", "available", None, "卡券列表占位，未连接真实核销数据。"),
]

rights = {
    "schema": "loveqigu.rights.v1",
    "version": "1.0.0",
    "source": "CH04_CONTENT_CANON_V1",
    "layer": "L1",
    "language_layer": "L1_COMMERCIAL",
    "status": "placeholder",
    "source_ref": SOURCE_REF,
    "story_ref": "data/story/ch04_chapters.json",
    "relic_ref": "data/relics/ch04_relics.json",
    "canonical_boundary": "CH04 Rights Layer placeholder factory. Commercial functions isolated from ritual chain. No new lore. No Canon Gap fill.",
    "chapter_context": chapter_context,
    "relic_refs_all": RELIC_IDS,
    "asset_boundary": {
        "rights": "L1 commercial layer; must not be sold as Relic or mixed into ritual closure.",
        "relic": "Story progression asset; Rights must not unlock or replace Relic progression.",
        "rule": "Rights records reference relic context but do not mutate Relic state.",
    },
    "rights": [],
}

for suffix, name, rtype, rstatus, node, copy in rights_template:
    rights["rights"].append(
        {
            "id": f"right_ch04_{suffix}",
            "name": name,
            "chapter_id": CHAPTER_ID,
            "type": rtype,
            "status": rstatus,
            "language_layer": "L1_COMMERCIAL",
            "relic_refs": RELIC_IDS,
            "description": f"记念《{CHAPTER_TITLE}》{name}。",
            "eligibility_node_id": node,
            "redemption": {"enabled": False, "surface": "结缘商城" if rtype != "share" else "分享页", "copy": copy},
            "canonical_boundary": "L1 commercial only; zero Relic progression effect; isolated from ritual closure.",
        }
    )

ar = {
    "schema": "loveqigu.ar.events.v1",
    "version": "1.0.0",
    "source": "CH04_CONTENT_CANON_V1",
    "layer": "L2",
    "language_layer": "L2_PRODUCT",
    "status": "placeholder",
    "source_ref": SOURCE_REF,
    "story_ref": "data/story/ch04_chapters.json",
    "relic_ref": "data/relics/ch04_relics.json",
    "rights_ref": "data/rights/ch04_rights.json",
    "canonical_boundary": "CH04 AR Event Layer placeholder factory. Field experience and closure entry. No new lore. No Canon Gap fill.",
    "chapter_context": chapter_context,
    "asset_boundary": {
        "ar_event": "Field visualization and approved closure entry; does not create 云门 state.",
        "relic": "AR output may reference Relic context; Relic progression remains deterministic from exploration.",
        "rights": "L1 redemption refs stay outside ritual closure chain.",
        "digital_collectible": "Share outputs are user-initiated; zero Relic progression effect.",
    },
    "events": [
        {
            "id": "ar_ch04_field_gate_v1",
            "code": "AR_CH04_FIELD_GATE_V1",
            "name": "初醒场域",
            "chapter_id": CHAPTER_ID,
            "node_id": "n1_field",
            "node_title": "场域·初醒到场",
            "status": "available",
            "interaction": "location_gate",
            "camera_enabled": False,
            "fake_ar_enabled": True,
            "description": "记念场域·初醒到场处的场域体验。田野初醒是 L2 章节题名，不是新地理或可被占有的关卡。",
            "copy": "预览初醒场域，不请求 live AR 权限。",
            "relic_refs": ["relic_ch04_awakening_badge", "relic_ch04_gate_imprint_d"],
            "rights_refs": [],
            "digital_collectible_refs": [],
            "canonical_boundary": "Field awakening visualization only; 田野初醒 is L2 chapter title, not new geography.",
        },
        {
            "id": "ar_ch04_imprint_awakening_v1",
            "code": "AR_CH04_IMPRINT_AWAKENING_V1",
            "name": "初醒残印",
            "chapter_id": CHAPTER_ID,
            "node_id": "n1_field",
            "node_title": "场域·初醒到场",
            "status": "available",
            "interaction": "imprint_particles",
            "camera_enabled": False,
            "fake_ar_enabled": True,
            "description": "记念场域处探索记录的初醒印迹显现。残印是连接曾经存在过的证据，不是收藏数量。",
            "copy": "预览初醒印迹粒子场域，不定义残印形成机制。",
            "relic_refs": ["relic_ch04_gate_imprint_d"],
            "rights_refs": [],
            "digital_collectible_refs": [],
            "canonical_boundary": "Does not define imprint formation mechanics; album D independent from prior chapters.",
        },
        {
            "id": "ar_ch04_awakening_awareness_v1",
            "code": "AR_CH04_AWAKENING_AWARENESS_V1",
            "name": "初醒镜照见",
            "chapter_id": CHAPTER_ID,
            "node_id": "n2_awakening",
            "node_title": "初醒镜·照见",
            "status": "available",
            "interaction": "awareness_prompt",
            "camera_enabled": False,
            "fake_ar_enabled": True,
            "description": "记念初醒镜·照见处的场域体验。照见，不是向外寻找答案，而是看见自己已与场域同在。",
            "copy": "预览初醒镜照见场域，承接第二处觉察。",
            "relic_refs": ["relic_ch04_awakening_mirror"],
            "rights_refs": [],
            "digital_collectible_refs": [],
            "canonical_boundary": "Uses existing field context only; no new Cosmology or lore.",
        },
        {
            "id": "ar_ch04_human_awakening_v1",
            "code": "AR_CH04_HUMAN_AWAKENING_V1",
            "name": "人间初醒场域",
            "chapter_id": CHAPTER_ID,
            "node_id": "n3_human_awakening",
            "node_title": "谷里咖啡·人间初醒",
            "status": "available",
            "interaction": "human_field_presence",
            "camera_enabled": False,
            "fake_ar_enabled": True,
            "description": "记念谷里咖啡·人间初醒处的场域体验。一次服务、一杯咖啡、一次真实相遇，连接仍可在真实相遇处被照见。",
            "copy": "预览人间初醒场域；结缘礼在探索完成后于结缘商城触达。",
            "relic_refs": ["relic_ch04_human_awakening"],
            "rights_refs": ["right_ch04_jieyuan_free_latte"],
            "digital_collectible_refs": [],
            "canonical_boundary": "L1 redemption stays outside ritual chain; no medical or lineage claims.",
        },
        {
            "id": "ar_ch04_awakening_guide_v1",
            "code": "AR_CH04_AWAKENING_GUIDE_V1",
            "name": "初醒修习引导",
            "chapter_id": CHAPTER_ID,
            "node_id": "n4_practice_awakening",
            "node_title": "云间书符·初醒修习",
            "status": "available",
            "interaction": "guide_sequence",
            "camera_enabled": False,
            "fake_ar_enabled": True,
            "description": "记念云间书符·初醒修习处的场域体验。修习是记念觉察被记存，不是获得新力量——符者，记念也，非咒也。",
            "copy": "预览初醒修习引导场域，不宣称医疗、派系或传承。",
            "relic_refs": ["relic_ch04_practice_awakening"],
            "rights_refs": [],
            "digital_collectible_refs": [],
            "canonical_boundary": "No medical claim, magic system, sect, or lineage; no L1 rights popup at practice node.",
        },
        {
            "id": "ar_ch04_completion_v1",
            "code": "AR_CH04_COMPLETION_V1",
            "name": "田野初醒·章成",
            "chapter_id": CHAPTER_ID,
            "node_id": "n5_complete",
            "node_title": "田野初醒·章成",
            "status": "locked",
            "interaction": "completion_scene",
            "camera_enabled": False,
            "fake_ar_enabled": True,
            "description": f"记念《{CHAPTER_TITLE}》章成 closure 场域。五处觉察已齐备，世界留下初醒印记，见证连接而非等级。",
            "copy": "预览章成 closure 场域，可接续分享海报生成流程。",
            "relic_refs": ["relic_ch04_field_awakening_seal"],
            "rights_refs": ["right_ch04_jieyuan_cafe_discount", "right_ch04_share_poster"],
            "digital_collectible_refs": ["dc_ch04_completion_poster"],
            "canonical_boundary": "Completion is not ranking, level, combat, or proof of superiority.",
            "unlock_requires": ["n1_field", "n2_awakening", "n3_human_awakening", "n4_practice_awakening"],
        },
    ],
}


def write(path: Path, data: dict) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    write(ROOT / "data/story/ch04_chapters.json", story)
    write(ROOT / "data/relics/ch04_relics.json", relics)
    write(ROOT / "data/rights/ch04_rights.json", rights)
    write(ROOT / "data/ar/ch04_ar-events.json", ar)
    print("CH04 placeholder factory written")
