module.exports = {
  "schema": "loveqigu.relics.v1",
  "version": "1.0.0",
  "source": "CH03_CONTENT_CANON_V1",
  "layer": "L2",
  "status": "active",
  "source_ref": "docs/content/CH03_CONTENT_CANON_V1.md",
  "story_ref": "data/story/ch03_chapters.json",
  "canonical_boundary": "CH03 Relic Layer. Story progression assets. Independent album C. No rarity, rank, level, or equipment semantics.",
  "asset_boundary": {
    "relic": "信物是故事进度资产，Canon-driven，见证连接而非拥有。",
    "digital_collectible": "数字藏品是营销与传播资产，与信物分离。",
    "rule": "Relic records must not be treated as Digital Collectible records."
  },
  "chapter_context": {
    "chapter_id": "ch03_field_reunion",
    "chapter_code": "CH03",
    "chapter_title": "再度重逢",
    "display_title": "《再度重逢》"
  },
  "relics": [
    {
      "id": "relic_ch03_reunion_badge",
      "name": "重逢徽章",
      "chapter_id": "ch03_field_reunion",
      "chapter_title": "再度重逢",
      "node_id": "n1_reunion",
      "node_title": "场域·重逢到场",
      "type": "awareness_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 1,
      "progression_role": "first_exploration_memorial",
      "description": "记念你在场域处完成的重逢到场。探索不是走向陌生，而是与曾被遗忘的连接再度重逢。",
      "awareness_line": "探索不是走向陌生，而是与曾被遗忘的连接再度重逢。",
      "canonical_boundary": "Reunion presence memorial; not a badge of rank or ownership.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "loot",
        "trophy"
      ]
    },
    {
      "id": "relic_ch03_gate_imprint_c",
      "name": "重逢残印·丙",
      "chapter_id": "ch03_field_reunion",
      "chapter_title": "再度重逢",
      "node_id": "n1_reunion",
      "node_title": "场域·重逢到场",
      "type": "imprint_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 1,
      "imprint_album_ref": "印谱 · 再度重逢",
      "progression_role": "imprint_album_slot",
      "description": "记念场域处留下的探索记录。残印是连接曾经存在过的证据，不是收藏数量。",
      "awareness_line": "场域之中，你留下了重逢被记存的记录。",
      "canonical_boundary": "Imprint evidence follows Canon tenth law; album C is independent from CH01 album A and CH02 album B.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "collectible_count",
        "power"
      ]
    },
    {
      "id": "relic_ch03_reunion_mirror",
      "name": "重逢镜信物",
      "chapter_id": "ch03_field_reunion",
      "chapter_title": "再度重逢",
      "node_id": "n2_remember",
      "node_title": "重逢镜·想起",
      "type": "awareness_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 2,
      "progression_role": "node_exploration_memorial",
      "description": "记念你在重逢镜处完成的想起。每一次发现都是一次重逢，每一次理解都是一次想起。",
      "awareness_line": "想起，不是向外寻找未知，而是与遗忘的连接再度重逢。",
      "canonical_boundary": "Reunion remembrance memorial only; third law alignment; no new Cosmology.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "loot",
        "trophy"
      ]
    },
    {
      "id": "relic_ch03_human_reunion",
      "name": "人间重逢信物",
      "chapter_id": "ch03_field_reunion",
      "chapter_title": "再度重逢",
      "node_id": "n3_human_reunion",
      "node_title": "谷里咖啡·人间重逢",
      "type": "awareness_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 3,
      "progression_role": "node_exploration_memorial",
      "description": "记念你在人间道场辨认到的重逢。一次服务、一杯咖啡、一次真实相遇，连接仍可与遗忘重逢。",
      "awareness_line": "人间道场不必在名山。与遗忘的重逢，可以在真实相遇处被想起。",
      "canonical_boundary": "Human-field reunion memorial only; L1 redemption stays outside ritual chain.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "loot",
        "trophy"
      ]
    },
    {
      "id": "relic_ch03_practice_reunion",
      "name": "云间书符·重逢感印",
      "chapter_id": "ch03_field_reunion",
      "chapter_title": "再度重逢",
      "node_id": "n4_practice_reunion",
      "node_title": "云间书符·重逢修习",
      "type": "practice_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 4,
      "progression_role": "practice_memorial",
      "description": "记念云间书符处完成的重逢修习。符者，记念也，非咒也——修习是想起连接曾被记存，不是获得新力量。",
      "awareness_line": "符者，记念也，非咒也。",
      "canonical_boundary": "Practice memorial only; no medical claim, magic system, sect, or lineage.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "loot",
        "trophy",
        "spell",
        "curse"
      ]
    },
    {
      "id": "relic_ch03_reunion_seal",
      "name": "重逢印记",
      "chapter_id": "ch03_field_reunion",
      "chapter_title": "再度重逢",
      "node_id": "n5_complete",
      "node_title": "再度重逢·章成",
      "type": "chapter_completion_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 5,
      "progression_role": "chapter_completion_mark",
      "completion_mark": true,
      "exploration_memorial": "再度重逢",
      "memorial_title": "重逢记念者",
      "description": "记念《再度重逢》章成。五处觉察已齐备，世界留下重逢印记，见证连接而非等级。",
      "awareness_line": "五处觉察已齐备。确认章成，点亮重逢印记。",
      "canonical_boundary": "Chapter completion seal only; not rank, level, combat, or superiority proof.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "achievement",
        "title_as_rank"
      ]
    }
  ]
};
