module.exports = {
  "schema": "loveqigu.relics.v1",
  "version": "1.0.0",
  "source": "CH05_CONTENT_CANON_V1",
  "layer": "L2",
  "status": "active",
  "source_ref": "docs/content/CH05_CONTENT_CANON_V1.md",
  "story_ref": "data/story/ch05_chapters.json",
  "canonical_boundary": "CH05 Relic Layer. Story progression assets. Independent album E. No rarity, rank, level, or equipment semantics.",
  "asset_boundary": {
    "relic": "信物是故事进度资产，Canon-driven，见证连接而非拥有。",
    "digital_collectible": "数字藏品是营销与传播资产，与信物分离。",
    "rule": "Relic records must not be treated as Digital Collectible records."
  },
  "chapter_context": {
    "chapter_id": "ch05_field_return",
    "chapter_code": "CH05",
    "chapter_title": "场域归位",
    "display_title": "《场域归位》"
  },
  "relics": [
    {
      "id": "relic_ch05_return_badge",
      "name": "归位徽章",
      "chapter_id": "ch05_field_return",
      "chapter_title": "场域归位",
      "node_id": "n1_field",
      "node_title": "场域·归位到场",
      "type": "awareness_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 1,
      "progression_role": "first_exploration_memorial",
      "description": "记念你在场域处完成的归位到场。觉察在场域中确认章成，连接仍在场域中被记存。",
      "awareness_line": "觉察在场域中确认章成，连接仍在场域中被记存。",
      "canonical_boundary": "Field return presence memorial; not a badge of rank or ownership.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "loot",
        "trophy"
      ]
    },
    {
      "id": "relic_ch05_gate_imprint_e",
      "name": "场域残印·戊",
      "chapter_id": "ch05_field_return",
      "chapter_title": "场域归位",
      "node_id": "n1_field",
      "node_title": "场域·归位到场",
      "type": "imprint_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 1,
      "imprint_album_ref": "印谱 · 场域归位",
      "progression_role": "imprint_album_slot",
      "description": "记念场域处留下的探索记录。残印是连接曾经存在过的证据，不是收藏数量。",
      "awareness_line": "场域之中，你留下了归位被记存的记录。",
      "canonical_boundary": "Imprint evidence follows Canon tenth law; album E is independent from prior chapter albums.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "loot",
        "trophy",
        "collectible_count",
        "power"
      ]
    },
    {
      "id": "relic_ch05_return_mirror",
      "name": "归位镜信物",
      "chapter_id": "ch05_field_return",
      "chapter_title": "场域归位",
      "node_id": "n2_return",
      "node_title": "归位镜·确认章成",
      "type": "awareness_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 2,
      "progression_role": "node_exploration_memorial",
      "description": "记念你在归位镜处完成确认章成。归位，不是离开，也不是抵达远方，而是在场中确认章成连接仍被记存。",
      "awareness_line": "归位，不是离开，也不是抵达远方，而是在场中确认章成连接仍被记存。",
      "canonical_boundary": "Return mirror memorial only; no new Cosmology.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "loot",
        "trophy"
      ]
    },
    {
      "id": "relic_ch05_human_return",
      "name": "人间归位信物",
      "chapter_id": "ch05_field_return",
      "chapter_title": "场域归位",
      "node_id": "n3_human_return",
      "node_title": "谷里咖啡·人间归位",
      "type": "awareness_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 3,
      "progression_role": "node_exploration_memorial",
      "description": "记念你在人间道场辨认到的归位。一次服务、一杯咖啡、一次真实相遇，连接仍可在真实相遇处被照见。",
      "awareness_line": "人间道场不必在名山。归位确认章成，可以在真实相遇处被记存。",
      "canonical_boundary": "Human-field return memorial only; L1 redemption stays outside ritual chain.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "loot",
        "trophy"
      ]
    },
    {
      "id": "relic_ch05_practice_return",
      "name": "云间书符·归位感印",
      "chapter_id": "ch05_field_return",
      "chapter_title": "场域归位",
      "node_id": "n4_practice_return",
      "node_title": "云间书符·归位修习",
      "type": "practice_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 4,
      "progression_role": "practice_memorial",
      "description": "记念云间书符处完成的归位修习。符者，记念也，非咒也——修习是记念觉察被记存，不是获得新力量。",
      "awareness_line": "符者，记念也，非咒也。",
      "canonical_boundary": "Practice memorial only; no medical claim, magic system, sect, or lineage.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "loot",
        "trophy",
        "spell",
        "curse"
      ]
    },
    {
      "id": "relic_ch05_field_return_seal",
      "name": "归位印记",
      "chapter_id": "ch05_field_return",
      "chapter_title": "场域归位",
      "node_id": "n5_complete",
      "node_title": "场域归位·章成",
      "type": "chapter_completion_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 5,
      "progression_role": "chapter_completion_mark",
      "completion_mark": true,
      "exploration_memorial": "场域归位",
      "memorial_title": "归位记念者",
      "description": "记念《场域归位》章成。五处觉察已齐备，世界留下归位印记，见证连接而非等级。",
      "awareness_line": "五处觉察已齐备。确认章成，点亮归位印记。",
      "canonical_boundary": "Chapter completion seal only; not rank, level, combat, or superiority proof.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "achievement",
        "title_as_rank"
      ]
    }
  ]
};
