module.exports = {
  "schema": "loveqigu.relics.v1",
  "version": "1.0.0",
  "source": "CH02_CONTENT_CANON_V1",
  "layer": "L2",
  "status": "active",
  "source_ref": "docs/content/CH02_CONTENT_CANON_V1.md",
  "story_ref": "data/story/ch02_chapters.json",
  "canonical_boundary": "CH02 Relic Layer. Story progression assets. Independent album B. No rarity, rank, level, or equipment semantics.",
  "asset_boundary": {
    "relic": "信物是故事进度资产，Canon-driven，见证连接而非拥有。",
    "digital_collectible": "数字藏品是营销与传播资产，与信物分离。",
    "rule": "信物记念与数字藏品分离：信物是故事进度资产，数字藏品是传播资产，二者不可混用。"
  },
  "chapter_context": {
    "chapter_id": "ch02_mountain_gate_echo",
    "chapter_code": "CH02",
    "chapter_title": "山门回响",
    "display_title": "《山门回响》"
  },
  "relics": [
    {
      "id": "relic_ch02_threshold_badge",
      "name": "门阈徽章",
      "chapter_id": "ch02_mountain_gate_echo",
      "chapter_title": "山门回响",
      "node_id": "n1_threshold",
      "node_title": "门阈·到场",
      "type": "awareness_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 1,
      "progression_role": "first_exploration_memorial",
      "description": "记念你在门阈处完成的到场。连接曾被看见，回响仍在场域中被辨认。",
      "awareness_line": "门阈之后，回响仍在。",
      "canonical_boundary": "Threshold presence memorial; not a badge of rank or ownership.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "loot",
        "trophy"
      ]
    },
    {
      "id": "relic_ch02_gate_imprint_b",
      "name": "山门残印·乙",
      "chapter_id": "ch02_mountain_gate_echo",
      "chapter_title": "山门回响",
      "node_id": "n1_threshold",
      "node_title": "门阈·到场",
      "type": "imprint_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 1,
      "imprint_album_ref": "印谱 · 山门回响",
      "progression_role": "imprint_album_slot",
      "description": "记念门阈处留下的探索记录。残印是连接曾经存在过的证据，不是收藏数量。",
      "awareness_line": "门阈之外，你留下了回响被记存的记录。",
      "canonical_boundary": "Imprint evidence follows Canon tenth law; album B is independent from CH01 album A.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "collectible_count",
        "power"
      ]
    },
    {
      "id": "relic_ch02_mirror_echo",
      "name": "回响镜信物",
      "chapter_id": "ch02_mountain_gate_echo",
      "chapter_title": "山门回响",
      "node_id": "n2_mirror",
      "node_title": "回响镜·辨认",
      "type": "awareness_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 2,
      "progression_role": "node_exploration_memorial",
      "description": "记念你在回响镜处完成的辨认。世界是一面回响之镜，探索不是向前夺取，而是看见连接如何被记存。",
      "awareness_line": "辨认，不是向外寻找答案，而是看见连接如何被世界记存。",
      "canonical_boundary": "Echo mirror memorial only; fourth law alignment; no new Cosmology.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "loot",
        "trophy"
      ]
    },
    {
      "id": "relic_ch02_human_echo",
      "name": "人间回响信物",
      "chapter_id": "ch02_mountain_gate_echo",
      "chapter_title": "山门回响",
      "node_id": "n3_human_echo",
      "node_title": "谷里咖啡·人间回响",
      "type": "awareness_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 3,
      "progression_role": "node_exploration_memorial",
      "description": "记念你在人间道场辨认到的回响。一次服务、一杯咖啡、一次真实相遇，连接的回响仍可被记存。",
      "awareness_line": "人间道场不必在名山。连接的回响，可以在真实相遇处被辨认。",
      "canonical_boundary": "Human-field echo memorial only; L1 redemption stays outside ritual chain.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "loot",
        "trophy"
      ]
    },
    {
      "id": "relic_ch02_practice_echo",
      "name": "云间书符·回响感印",
      "chapter_id": "ch02_mountain_gate_echo",
      "chapter_title": "山门回响",
      "node_id": "n4_practice_echo",
      "node_title": "云间书符·记念修习",
      "type": "practice_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 4,
      "progression_role": "practice_memorial",
      "description": "记念云间书符处完成的记念修习。符者，记念也，非咒也——修习是辨认回响被记存，不是获得新力量。",
      "awareness_line": "符者，记念也，非咒也。",
      "canonical_boundary": "Practice memorial only; no medical claim, magic system, sect, or lineage.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "loot",
        "trophy",
        "spell",
        "curse"
      ]
    },
    {
      "id": "relic_ch02_mountain_echo_seal",
      "name": "回响印记",
      "chapter_id": "ch02_mountain_gate_echo",
      "chapter_title": "山门回响",
      "node_id": "n5_complete",
      "node_title": "山门回响·章成",
      "type": "chapter_completion_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 5,
      "progression_role": "chapter_completion_mark",
      "completion_mark": true,
      "exploration_memorial": "山门回响",
      "memorial_title": "回响辨认者",
      "description": "记念《山门回响》章成。五处觉察已齐备，世界留下回响印记，见证连接而非等级。",
      "awareness_line": "五处觉察已齐备。确认章成，点亮回响印记。",
      "canonical_boundary": "Chapter completion seal only; not rank, level, combat, or superiority proof.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "achievement",
        "title_as_rank"
      ]
    }
  ]
};
