module.exports = {
  "schema": "loveqigu.relics.v1",
  "version": "1.0.0",
  "source": "CH07_CONTENT_CANON_V1",
  "layer": "L2",
  "status": "active",
  "source_ref": "docs/content/canon/CH07_CONTENT_CANON_V1.md",
  "story_ref": "data/story/ch07_chapters.json",
  "canonical_boundary": "CH07 Relic Layer. Story progression assets. Independent album G. No rarity, rank, level, or equipment semantics.",
  "asset_boundary": {
    "relic": "信物是故事进度资产，Canon-driven，见证连接而非拥有。",
    "digital_collectible": "数字藏品是营销与传播资产，与信物分离。",
    "rule": "信物记念与数字藏品分离：信物是故事进度资产，数字藏品是传播资产，二者不可混用。"
  },
  "chapter_context": {
    "chapter_id": "ch07_field_echo",
    "chapter_code": "CH07",
    "chapter_title": "回响之路",
    "display_title": "《回响之路》"
  },
  "relics": [
    {
      "id": "relic_ch07_echo_badge",
      "name": "回响徽章",
      "chapter_id": "ch07_field_echo",
      "chapter_title": "回响之路",
      "node_id": "n1_field",
      "node_title": "场域·回响种子",
      "type": "awareness_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 1,
      "progression_role": "first_exploration_memorial",
      "description": "记念你在场域处辨认到的回响种子。觉察开始离开自身，连接仍在场域中被记存。",
      "awareness_line": "觉察开始离开自身，连接仍在场域中被记存。",
      "canonical_boundary": "Echo seed presence memorial; not a badge of rank or ownership.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "loot",
        "trophy"
      ]
    },
    {
      "id": "relic_ch07_gate_imprint_g",
      "name": "场域残印·庚",
      "chapter_id": "ch07_field_echo",
      "chapter_title": "回响之路",
      "node_id": "n1_field",
      "node_title": "场域·回响种子",
      "type": "imprint_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 1,
      "imprint_album_ref": "印谱 · 回响之路",
      "progression_role": "imprint_album_slot",
      "description": "记念场域处留下的探索记录。残印是连接曾经存在过的证据，不是收藏数量。",
      "awareness_line": "场域之中，你留下了回响被记存的记录。",
      "canonical_boundary": "Imprint evidence follows Canon tenth law; album G is independent from prior chapter albums.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "loot",
        "trophy",
        "collectible_count",
        "power"
      ]
    },
    {
      "id": "relic_ch07_echo_mirror",
      "name": "回响镜信物",
      "chapter_id": "ch07_field_echo",
      "chapter_title": "回响之路",
      "node_id": "n2_reflection",
      "node_title": "回响镜·照见",
      "type": "awareness_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 2,
      "progression_role": "node_exploration_memorial",
      "description": "记念你在回响镜处完成的照见。改变开始影响周围的人，连接在照见处被记存。",
      "awareness_line": "改变开始影响周围的人，连接在照见处被记存。",
      "canonical_boundary": "Echo mirror memorial only; no new Cosmology.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "loot",
        "trophy"
      ]
    },
    {
      "id": "relic_ch07_human_connection",
      "name": "人间连接信物",
      "chapter_id": "ch07_field_echo",
      "chapter_title": "回响之路",
      "node_id": "n3_human_connection",
      "node_title": "谷里咖啡·人间连接",
      "type": "awareness_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 3,
      "progression_role": "node_exploration_memorial",
      "description": "记念你在人间道场辨认到的连接。一次服务、一杯咖啡、一次真实相遇，善意连接仍可在真实相遇处被照见。",
      "awareness_line": "人间道场不必在名山。同行的记念，可以在真实相遇处被记存。",
      "canonical_boundary": "Human connection memorial only; L1 redemption stays outside ritual chain.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "loot",
        "trophy"
      ]
    },
    {
      "id": "relic_ch07_practice_echo",
      "name": "云间书符·同行感印",
      "chapter_id": "ch07_field_echo",
      "chapter_title": "回响之路",
      "node_id": "n4_practice_echo",
      "node_title": "云间书符·同行修习",
      "type": "practice_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 4,
      "progression_role": "practice_memorial",
      "description": "记念云间书符处完成的同行修习。符者，记念也，非咒也——修习是记念觉察被记存，不是获得新力量。",
      "awareness_line": "符者，记念也，非咒也。",
      "canonical_boundary": "Practice memorial only; no medical claim, magic system, sect, or lineage.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "loot",
        "trophy",
        "spell",
        "curse"
      ]
    },
    {
      "id": "relic_ch07_field_echo_seal",
      "name": "回响印记",
      "chapter_id": "ch07_field_echo",
      "chapter_title": "回响之路",
      "node_id": "n5_complete",
      "node_title": "回响之路·章成",
      "type": "chapter_completion_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 5,
      "progression_role": "chapter_completion_mark",
      "completion_mark": true,
      "exploration_memorial": "回响之路",
      "memorial_title": "回响同行者",
      "description": "记念《回响之路》章成。五处觉察已齐备，世界留下回响印记，见证连接而非等级。",
      "awareness_line": "五处觉察已齐备。确认章成，点亮回响印记。",
      "canonical_boundary": "Chapter completion seal only; not rank, level, combat, or superiority proof.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "achievement",
        "title_as_rank"
      ]
    }
  ]
};
