module.exports = {
  "schema": "loveqigu.relics.v1",
  "version": "1.0.0",
  "source": "CH09_CONTENT_CANON_V1",
  "layer": "L2",
  "status": "active",
  "source_ref": "docs/content/canon/CH09_CONTENT_CANON_V1.md",
  "story_ref": "data/story/ch09_chapters.json",
  "canonical_boundary": "CH09 Relic Layer. Story progression assets. Independent album H. No rarity, rank, level, or equipment semantics.",
  "asset_boundary": {
    "relic": "信物是故事进度资产，Canon-driven，见证未来之约而非拥有。",
    "digital_collectible": "数字藏品是营销与传播资产，与信物分离。",
    "rule": "Relic records must not be treated as Digital Collectible records."
  },
  "chapter_context": {
    "chapter_id": "ch09_field_echo_future",
    "chapter_code": "CH09",
    "chapter_title": "未来之约",
    "display_title": "《未来之约》"
  },
  "relics": [
    {
      "id": "relic_ch09_future_badge",
      "name": "未来徽章",
      "chapter_id": "ch09_field_echo_future",
      "chapter_title": "未来之约",
      "node_id": "n1_future",
      "node_title": "场域·未来种子",
      "type": "awareness_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 1,
      "progression_role": "first_exploration_memorial",
      "description": "记念你在场域处辨认到的未来种子。传承的延续开始外显，连接仍在场域中被记存。",
      "awareness_line": "传承的延续开始外显，连接仍在场域中被记存。",
      "canonical_boundary": "Future seed presence memorial; not a badge of rank or ownership.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "loot",
        "trophy"
      ]
    },
    {
      "id": "relic_ch09_gate_imprint_h",
      "name": "场域残印·辛",
      "chapter_id": "ch09_field_echo_future",
      "chapter_title": "未来之约",
      "node_id": "n1_future",
      "node_title": "场域·未来种子",
      "type": "imprint_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 1,
      "imprint_album_ref": "印谱 · 未来之约",
      "progression_role": "imprint_album_slot",
      "description": "记念场域处留下的探索记录。残印是连接曾经存在过的证据，不是收藏数量。",
      "awareness_line": "场域之中，你留下了未来被记存的记录。",
      "canonical_boundary": "Imprint evidence follows Canon tenth law; album H is independent from prior chapter albums.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "loot",
        "trophy",
        "collectible_count",
        "power"
      ]
    },
    {
      "id": "relic_ch09_collective_echo_mirror",
      "name": "集体回响信物",
      "chapter_id": "ch09_field_echo_future",
      "chapter_title": "未来之约",
      "node_id": "n2_collective_echo",
      "node_title": "回响镜·集体回响",
      "type": "awareness_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 2,
      "progression_role": "node_exploration_memorial",
      "description": "记念你在集体回响处完成的觉察。影响开始在社会互动中被照见，共鸣在回响处被记存。",
      "awareness_line": "影响开始在社会互动中被照见，共鸣在回响处被记存。",
      "canonical_boundary": "Collective echo memorial only; no new Cosmology.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "loot",
        "trophy"
      ]
    },
    {
      "id": "relic_ch09_extended_connections",
      "name": "连接延伸信物",
      "chapter_id": "ch09_field_echo_future",
      "chapter_title": "未来之约",
      "node_id": "n3_extended_connections",
      "node_title": "谷里咖啡·连接延伸",
      "type": "awareness_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 3,
      "progression_role": "node_exploration_memorial",
      "description": "记念你在人间道场辨认到的连接延伸。一次服务、一杯咖啡、一次真实相遇，善意连接仍可在真实相遇处被照见。",
      "awareness_line": "人间道场不必在名山。同行的记念，可以在真实相遇处被记存。",
      "canonical_boundary": "Extended connections memorial only; L1 redemption stays outside ritual chain.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "loot",
        "trophy"
      ]
    },
    {
      "id": "relic_ch09_social_impact",
      "name": "云间书符·社会感印",
      "chapter_id": "ch09_field_echo_future",
      "chapter_title": "未来之约",
      "node_id": "n4_social_impact",
      "node_title": "云间书符·社会影响",
      "type": "practice_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 4,
      "progression_role": "practice_memorial",
      "description": "记念云间书符处完成的社会影响修习。符者，记念也，非咒也——修习是记念觉察被记存，不是获得新力量。",
      "awareness_line": "符者，记念也，非咒也。",
      "canonical_boundary": "Social impact memorial only; no medical claim, magic system, sect, or lineage.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "loot",
        "trophy",
        "spell",
        "curse"
      ]
    },
    {
      "id": "relic_ch09_field_future_seal",
      "name": "未来印记",
      "chapter_id": "ch09_field_echo_future",
      "chapter_title": "未来之约",
      "node_id": "n5_complete",
      "node_title": "未来之约·章成",
      "type": "chapter_completion_relic",
      "asset_class": "story_progression",
      "language_layer": "L3_CANON_RITUAL_WORLDVIEW",
      "status": "unrecorded",
      "imprint_slot": 5,
      "progression_role": "chapter_completion_mark",
      "completion_mark": true,
      "exploration_memorial": "未来之约",
      "memorial_title": "未来同行者",
      "description": "记念《未来之约》章成。五处觉察已齐备，世界留下未来印记，见证连接而非等级。",
      "awareness_line": "五处觉察已齐备。确认章成，点亮未来印记。",
      "canonical_boundary": "Chapter completion seal only; not rank, level, combat, or superiority proof.",
      "forbidden_semantics": [
        "rarity",
        "level",
        "grade",
        "rank",
        "equipment",
        "achievement",
        "title_as_rank"
      ]
    }
  ]
};
